apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - name: fabric-volume
        mountPath: /var/hyperledger/fabric          
      - name: fabric-volume-org1
        mountPath: /org1
      - name: fabric-volume-org2
        mountPath: /org2
      - name: fabric-volume-org3
        mountPath: /org3             
  volumes:
      - name: fabric-volume
        persistentVolumeClaim:
          claimName: fabric-org0
      - name: fabric-volume-org1
        persistentVolumeClaim:
          claimName: fabric-org1
      - name: fabric-volume-org2
        persistentVolumeClaim:
          claimName: fabric-org2
      - name: fabric-volume-org3
        persistentVolumeClaim:
          claimName: fabric-org3          
                      