kubectl delete -f fabric-ca-deployment-orderer.yaml 
kubectl delete -f fabric-ca-deployment-org1.yaml
kubectl delete -f fabric-ca-deployment-org2.yaml
kubectl delete -f fabric-ca-deployment-org3.yaml
kubectl delete -f job_orderercert.yaml 
kubectl delete -f job_org1cert.yaml
kubectl delete -f job_org2cert.yaml
kubectl delete -f job_org3cert.yaml
kubectl delete -f create-artifacts.yaml