---


apiVersion: v1
kind: Service
metadata:
  name: ca-org1
spec:
  selector:
    app: ca-org1
  ports:
  - protocol: TCP
    port: 7054
    targetPort: 7054
    name: https    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org1
  labels: 
    app: ca-org1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-org1
  template:
    metadata:
      labels:
        app: ca-org1
    spec:
      volumes:
      - name: org1-ca
        persistentVolumeClaim:
          claimName: org1-pvc
      - name: redis-storage
        persistentVolumeClaim:
          claimName: mypvc

      containers:
      - name: ca-org1
        image: hyperledger/fabric-ca:1.4.4
        command: 
          - "sh"
          - "-c" 
          - "sleep 1 && fabric-ca-server start -b admin:adminpw -d --cfg.identities.allowremove --port 7054"
        env:
        - name: FABRIC_CA_SERVER_HOME
          value: /organizations/fabric-ca/ca-org1/
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "ca-org1"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_CSR_CN
          value: "ca-org1"
        - name: FABRIC_CA_SERVER_CSR_HOSTS
          value: ca-org1           
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: GODEBUG
          value: "netdns=go"
        # - name: FABRIC_CA_CLIENT_HOME
        #   value: /organizations/peerOrganizations/org1.example.com/
        volumeMounts:
        - name: org1-ca
          mountPath: /organizations
        - name: redis-storage   
          mountPath: /scripts
                                        
        ports:
        - containerPort: 7054
