kind: Service
apiVersion: v1
metadata:
  name: peer0-org3
  labels:
    app: peer0-org3
spec:
  selector:
    name: peer0-org3
  type: ClusterIP
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
    - name: event
      port: 7061
      protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org3
spec:
  selector:
    matchLabels:
      name: peer0.org3.example.com
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0.org3.example.com
    spec:
      volumes:
        - name: org3-peer
          persistentVolumeClaim:
            claimName: org3-pvc  
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: mypvc

      containers:
        - name: peer0-org3
          image: hyperledger/fabric-peer:2.3
          command: ["sh", "-c", "peer node start"]
          env:
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: peer0.org3.example.com
            - name: CORE_PEER_ADDRESS
              value: peer0.org3.example.com:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_EVENTS_ADDRESS
              value: 0.0.0.0:7061
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0.org3.example.com:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0.org3.example.com:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0.org3.example.com:7051
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "true"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_LOCALMSPID
              value: Org3MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
            # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
            #   value: "user"
            # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
            #   value: "password"                            
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443

          ports:    
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
            - containerPort: 9443
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
            requests:
              memory: "250Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/chaincode/
              name: fabricfiles
              subPath: chaincode/
            - mountPath: /organizations
              name: org3-peer
            - mountPath: /var/hyperledger/production
              name: org3-peer
              subPath: state/org3/peer0

        - name: couchdb
          image: hyperledger/fabric-couchdb:0.4.15
          # env:
          # - name: COUCHDB_USER
          #   value: "user"
          # - name: COUCHDB_PASSWORD
          #   value: "password"
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
            requests:
              memory: "250Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: org3-peer
              subPath: state/org3/peer0-couchdb
